# Generated by Django 4.2.8 on 2024-04-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiscImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(help_text='Please compress image and convert type to webp before uploading. https://imagecompressor.com/, https://cloudconvert.com/webp-converter', null=True, upload_to='main_app.File/bytes/filename/mimetype')),
            ],
        ),
    ]
