# Generated by Django 4.2.8 on 2024-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('role_or_description', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('information_body', models.TextField(max_length=3000)),
                ('image', models.ImageField(help_text='Please compress image and convert type to webp before uploading. https://imagecompressor.com/, https://cloudconvert.com/webp-converter', null=True, upload_to='main_app.File/bytes/filename/mimetype')),
            ],
        ),
        migrations.DeleteModel(
            name='MiscImage',
        ),
    ]
