# Generated by Django 4.2.8 on 2024-04-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='role_or_description',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='Please compress logo and convert type to webp before uploading. https://imagecompressor.com/, https://cloudconvert.com/webp-converter', null=True, upload_to='main_app.File/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='information_body',
            field=models.TextField(help_text='Enter a detailed description of the project or organization.', max_length=3000),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(help_text="Enter the link to the final product or to the organization's home page.", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text="Enter the project or organization's name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.CharField(help_text='Enter the technical skills used.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_id',
            field=models.CharField(help_text='Enter an unique id.', max_length=100),
        ),
    ]
