# Generated by Django 4.2.8 on 2024-05-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_project_period_project_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_date', models.DateTimeField()),
                ('file', models.FileField(upload_to='main_app.File/bytes/filename/mimetype')),
            ],
        ),
    ]
