# Generated by Django 4.2.8 on 2024-05-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='uploaded_date',
        ),
    ]
